Lesson16
dimasumskoy/rails-thinknetica pull request #2
Opened 2017-06-05 16:41 UTC by dimasumskoy

Очень не уверен насчет отображения мест в вагоне в зависимости от его типа. Логика отображения получилась в виде, пока не знаю как это можно распределить правильно.
Вагоны на странице поезда сразу показываются в зависимости от значения флага, передал сортированный список в вид через контроллер.

2017-06-06 07:11 UTC, vkurennov requested changes

2017-06-06 07:11 UTC, vkurennov commented on tutu/app/models/railcar.rb
> +      self.number = self.train.railcars.last.number + 1
Тут есть проблема: по-умолчанию, ассоциации сортиируются по полю updated_at, поэтому может оказаться последним вагон не с максимальным номером, а тот, который последним редактировался. Поэтому надо либо брать максимальный номер (метод `maximum`), либо явно применить сортировку по номеру. Но вариант с maximum будет быстрее, т.к. все сделает база.

2017-06-06 07:11 UTC, vkurennov commented on tutu/app/models/train.rb
> +    sorted = self.railcars.order(:number)
Лучше сделать скоуп c параметром в модели Railcar, который будет возвращать прямой или обратный порядок, а здесь обратиться к этому скоупу и в качесвте параметра передать флаг `sorting_from_head`

2017-06-06 07:11 UTC, vkurennov commented on tutu/app/models/train.rb
> +      sorted.reverse
Это медленная сортировка, т.к. сначала ты достаешь все из базы, а потом уже переворачиваешь эту коллекцию средствами руби. Гораздо эффективнее сразу из базы достать коллекцию в обратном порядке. Как это сделать лучше - см. комментарий выше

2017-06-06 07:11 UTC, vkurennov commented on tutu/app/models/train.rb
> +    self.railcars.where(type: railcar_type).inject(0) { |sum, railcar| sum + railcar.send(seat_type.to_sym) }
У нас есть метод sum, благодаря которому, сама база подсчитает сумму и вернет число. Это значительно быстрее и эффективнее, чем загрузка коллекции в память и подсчет средствами руби

2017-06-06 07:11 UTC, vkurennov commented on tutu/app/views/railcars/_form.html.erb
> +    <%= form.text_field :type, id: :railcar_type %>
Почему это текстовое поле? Откуда пользователь должен знать, какие типы вагонов существуют? Сделай выпадающий список.

2017-06-06 07:11 UTC, vkurennov commented on tutu/app/views/railcars/show.html.erb
> +    <% case @railcar.type %>
Вместо case тут можно применить принцип convention over configuration: сделай для каждого типа вагона свой паршл и назови его по имени класса. Например, для `CoupeRailcar` паршл будет `_coupe_railcar` и т.п. Тогда используя атрибут `type` легко отрендерить нужный паршл, только чтобы преобразовать название типа в `snake_case`, нужно будет применить метод `underscore`

2017-06-08 06:06 UTC, iBublik requested changes

2017-06-08 06:06 UTC, iBublik commented on tutu/app/controllers/railcars_controller.rb
> +    @railcar = Railcar.find(params[:id]).becomes(Railcar)
Это преобразование делать необязательно. Можно ведь явно указывать `redirect_to railcar_path(@railcar)`, таким образом `becomes` будет нужен только в форме.

2017-06-08 06:06 UTC, iBublik commented on tutu/app/models/railcar.rb
> +  def set_number
Номер вагона будет меняться при каждом сохранении - лучше задавать его только в тот момент, когда он еще не задан.
И еще можно уложиться в одну строку и один запрос, упростив метод - `train.railcars.maximum(:number).to_i + 1`

2017-06-08 06:06 UTC, iBublik commented on tutu/app/models/railway_stations_route.rb
> +  validates :railway_station_id, uniqueness: { scope: :route_id }
А почему в названии поля `id`? Это ведь не идентификатор, а номер/позиция

2017-06-08 06:06 UTC, iBublik commented on tutu/app/models/route.rb
> +  before_validation :stations_amount
В данном случае нужно не коллбэк использовать, а кастомную валидацию - для этого есть метод `validate` (без `s` на конце)

2017-06-08 06:06 UTC, iBublik commented on tutu/app/models/train.rb
> +  def sort_railcars
Название метода неудачное - создается впечатление, что это команда, которая что-то меняет в базе. Но это ведь запрос, он просто отдает результат. Такие методы-запросы обычно не содержат глаголов в именах, в данном случае можно назвать `sorted_railcars`

2017-06-08 06:06 UTC, iBublik commented on tutu/app/models/train.rb
> +    Railcar.sort(direction)
У тебя возвращаются вообще все вагоны, а нужны только принадлежащие этому поезду

2017-06-08 06:06 UTC, iBublik commented on tutu/app/models/train.rb
> +    Railcar.where(type: railcar_type).sum(seat_type.to_sym)
Аналогично - нужна сумма по вагонам этого поезда

2017-06-08 06:06 UTC, iBublik commented on tutu/app/views/railcars/_economy_railcar.html.erb
> +	<li><%= "Боковые нижние места: #{@railcar.side_bottom_seats}" %></li>
Отступ поехал

2017-06-08 06:06 UTC, iBublik commented on tutu/app/views/railcars/_railcar.html.erb
> +    <% main_railcar = railcar.becomes(Railcar) %>
Можно без `becomes` обойтись, просто используй `railcar_path(railcar)`

2017-06-08 06:06 UTC, iBublik commented on tutu/db/migrate/20170603144151_add_variety_seats_to_railcar.rb
> +    add_column :railcars, :number, :integer
Если меняешь одну таблицу, можно использовать `change_table`

2017-06-08 06:06 UTC, iBublik commented on tutu/db/migrate/20170605114623_add_sorting_flag_to_trains.rb
> +    add_column :trains, :sorting_from_head, :boolean
`default: false, null: false` - чтоб поле одержало только логические значения (без `null`)

2017-06-08 06:06 UTC, iBublik commented on tutu/db/migrate/20170602172059_add_position_in_railway_stations_routes.rb
> +    add_reference :railway_stations_routes, :station_position, foreign_key: true, index: true
Странная миграция. `add_refernce` используется для создания связи между двумя таблицами (например между вагонов и поездом), а тут у тебя таблица `railway_stations_routes` пытается связаться с несуществующей `station_positions`. По схеме видно, что даже внешний ключ не добавился, хотя в миграции он указан. В общем, нужно обычное поле добавлять, без всяких связей

2017-06-08 16:25 UTC, iBublik requested changes

2017-06-08 16:25 UTC, iBublik commented on tutu/app/models/application_record.rb
> +  include ActiveModel::Dirty
А зачем это делать? В `ActiveRecord` уже подключен этот модуль

2017-06-08 16:25 UTC, iBublik commented on tutu/app/models/railcar.rb
> +    self.number = 1 if train.railcars.empty?
Эта строка не нужна, ты ведь ниже снова присваиваешь значение

2017-06-08 16:25 UTC, iBublik commented on tutu/app/models/railway_station.rb
> +  scope :position_list, ->(route) do
Название должно отражать суть происходящего. Вот заглядываешь ты в код чужого приложения, видишь там `route.railway_station.position_list` - ты догадаешься, что он возвращает отсортированные станции? :) А вот назвав скоуп `sorted`, это сразу видно

2017-06-08 16:25 UTC, iBublik commented on tutu/app/models/railway_station.rb
> +    joins(:railway_stations_routes).where(["railway_stations_routes.route_id = ?", route]).order("railway_stations_routes.station_position_id")
Можно кстати использовать хэш-нотацию и писать более "красиво" - `where(railway_stations_routes: { route_id: route })`

2017-06-08 16:25 UTC, iBublik commented on tutu/app/models/railcar.rb
> +  scope :sort_all, ->(direct_sorting) { direct_sorting ? order(:number) : order("number DESC") }
Нейминг опять создает впечатление команды - "отсортируй мне вагоны". В именах методов-запросов не используются глаголы. Так что `sorted` тут предпочтительнее.

2017-06-08 16:25 UTC, iBublik commented on tutu/db/migrate/20170608142313_add_default_value_to_trains_flag.rb
> +    change_table :trains do |t|
Не нужно плодить миграции - если ты в рамках фичи добавил что-то, а потом это понадобилось изменить, то просто откатывай миграцию, вноси изменения и накатывай снова.

2017-06-08 16:25 UTC, iBublik commented on tutu/db/migrate/20170608142313_add_default_value_to_trains_flag.rb
> +    change_table :trains do |t|
Как откатывать миграции я рассказывал [тут](http://connect.thinknetica.com/t/denis-toriczyn-zorro/4119/215?u=artpyankov)

2017-06-08 16:25 UTC, iBublik commented on tutu/app/models/railway_station.rb
> +    joins(:railway_stations_routes).where(["railway_stations_routes.route_id = ?", route]).order("railway_stations_routes.station_position_id")
И почему тут `station_position_id`? Должно ведь быть `station_position`

2017-06-08 16:25 UTC, iBublik commented on tutu/db/migrate/20170608144347_change_railway_stations_routes_table.rb
> +      t.integer :station_position
Что-то я уже запутался в миграциях, Зачем тут удаление и сразу добавление одного и того же поля?

2017-06-08 16:25 UTC, iBublik commented on tutu/db/migrate/20170608144818_remove_column_from_railway_stations_routes.rb
> +    remove_column :railway_stations_routes, :station_position, :integer
А тут опять удаление.. В итоге этого поля в таблице нет :)

2017-06-08 16:25 UTC, iBublik commented on tutu/db/schema.rb
> +    t.integer "station_position_id"
Не должно быть такого поля у нас :) должно быть поле `station_position`
У тебя страшная путаница в миграциях. Проще всего будет переключиться на master ветку, сделать `rake db:reset` (это удалит базу и создаст заново, данные потеряются правда), потом снова переключиться на эту ветку и поправить миграции (удалить ненужные, исправить остальные). По этому заданию у нас должно быть 3 миграции:
1. Изменение таблицы вагонов (добавление полей под места, порядкового номера для сортировка, переименование kind в type)
2. Добавление логического поля сортировки в поезда
3. Добавление поля-порядкового номера для связующей таблицы маршрута и станции

2017-06-09 07:57 UTC, vkurennov approved these changes

2017-06-09 17:28 UTC, merged