Lesson17
dimasumskoy/rails-thinknetica pull request #3
Opened 2017-06-13 15:02 UTC by dimasumskoy

Не уверен насчет контроеллера билета. По заданию нужно создать связанный с пользователем билет, но через вложенные ресурсы не получается сделать переход на создание билета со страницы поиска и с передачей аргументов (id поезда, маршрута и т.д).

2017-06-14 05:22 UTC, iBublik requested changes

2017-06-14 05:22 UTC, iBublik commented on tutu/app/controllers/railcars_controller.rb
>  class RailcarsController < ApplicationController
train_id теперь берется из url, поэтому нужно убрать это значение из railcar_params

2017-06-14 05:22 UTC, iBublik commented on tutu/app/controllers/searches_controller.rb
> +  def find_route_trains
Лучше ограничиваться стандартным CRUD-экшенами в контроллерах - так они остаются максимально простыми. В данном случае можно оставить экшены show (запрос страницы поиска) и create (собственно операция поиска, т.е. его "создание"). А вьюху вообще одну оставить - только show

2017-06-14 05:22 UTC, iBublik commented on tutu/app/controllers/searches_controller.rb
> +    @route = RailwayStation.find_route(get_first_station_id, get_last_station_id)
Довольно странно, что метода класса `RailwayStation` возвращает маршрут. Логичнее в сами маршруты и перенести метод.
И еще, маршрутов с такими станциями может быть несколько, так что нужно их все возвращать, а не одну

2017-06-14 05:22 UTC, iBublik commented on tutu/app/controllers/searches_controller.rb
> +  def show_route_trains
Не вижу причин выносить это в отдельный экшен. Часть переменных вообще избыточна - например, `@route_name` и `@route.trains` мы можем и во вьюхе получить, у нас ведь есть `@route`.

2017-06-14 05:22 UTC, iBublik commented on tutu/app/controllers/searches_controller.rb
> +  def show_route_trains
Но если хочется, можно выделить это все в отдельный класс `Search` (просто Ruby класс, не ActiveRecord), и делать например так:
```ruby
@search = Search.new(start_station_id, end_station_id).perform
# возвращает начальную станцию поиска
@search.start_station
# возвращает список поездов
@search.trains
# другие полезные методы
...
```

2017-06-14 05:22 UTC, iBublik commented on tutu/app/controllers/searches_controller.rb
> +    @departure_time = @route.railway_stations.first.current_departure_time(@route)
Пользователю хотелось бы видеть информацию по запрошенным станциям, а не просто первой/последней станции маршрута

2017-06-14 05:22 UTC, iBublik commented on tutu/app/controllers/searches_controller.rb
> +  def get_first_station_id
Методы с префиксом `get/set` в Ruby не используются - лучше просто `first_station_id`

2017-06-14 05:22 UTC, iBublik commented on tutu/app/controllers/tickets_controller.rb
> +    @user = User.new(user_params)
Можешь просто `User.first` сделать, не надо создавать пользователя. Далее мы реализуем аутентификацию и будем привязывать билет к текущему авторизованному пользователю

2017-06-14 05:22 UTC, iBublik commented on tutu/app/models/railway_station.rb
> +    Route.all.select { |route| route.railway_station_ids == [first_station_id, last_station_id] }.first
Перебирать все созданные маршруты в памяти неэффективно - можно реализовать это запросом (выбираем маршруты с начальной станций, с конечной, уже на Ruby получаем пересечение этих множеств). К тому же у тебя сейчас выбираются маршруты, состоящие всего их 2 станций. Нам надо искать маршруты, в которых присутствуют указанные станции, но в целом их может быть больше. На порядок пока можешь забить, это не обязательно проверять

2017-06-14 05:22 UTC, iBublik commented on tutu/app/models/search.rb
> +class Search < ApplicationRecord
Если делать такой класс, то точно не ActiveRecord - в базе мы не будем хранить поисковые запросы

2017-06-14 05:22 UTC, iBublik commented on tutu/app/views/railcars/edit.html.erb
> +<%= render 'form', railcar: @railcar.becomes(Railcar), train: @train %>
В принципе, можно при создании вагона сразу его привязывать к поезду, тогда не потребуется передавать поезд отдельным параметром (можно во вьюхе использовать `@railcar.train`)

2017-06-14 05:22 UTC, iBublik commented on tutu/app/views/railcars/new.html.erb
> +<%= render 'form', railcar: @railcar.becomes(Railcar), train: @train %>
Аналогично комменту выше

2017-06-14 05:22 UTC, iBublik commented on tutu/app/views/searches/show_route_trains.html.erb
> +<% @depart_station = @route.railway_stations.first %>
Во вьюхах нет смысла создавать инстанс переменные - лучше уж просто локальные. А еще лучше чтоб вьюхи работали только с существующими объектами и вызывали их методы.

2017-06-14 05:22 UTC, iBublik commented on tutu/app/views/tickets/show.html.erb
> +	<b>Маршрут: </b> <%= "#{@ticket.depart_station.title} - #{@ticket.arrive_station.title}" %>
Внезапно tab вместо пробела :)

2017-06-14 05:22 UTC, iBublik commented on tutu/config/routes.rb
> +  resource :search, only: [:new, :show, :edit] do
Зачем столько роутов? У тебя по факту используются только show и find_route_stations

2017-06-14 18:48 UTC, dimasumskoy commented on tutu/app/controllers/searches_controller.rb
> +  def find_route_trains
Ну я так сделал из предположений, что поиск может быть не только по поездам в маршрутах, а еще по другим критериям, и что для каждого такого критерия нужны будут свои экшены и вьюхи. Но это уже уклон в свои додумывания идет, что не всегда хорошо. (:

2017-06-14 18:54 UTC, dimasumskoy commented on tutu/app/controllers/searches_controller.rb
> +    @route = RailwayStation.find_route(get_first_station_id, get_last_station_id)
Сначала и сделал в маршруте, но потом подумал, что т.к. в аргумент мы передаем станции, из которых и строится и ищется маршрут, то логичней это отдать классу станций. Пока еще от неуверенности и неопытности часто путаюсь в суждениях что к чему/куда/зачем

2017-06-14 18:57 UTC, dimasumskoy commented on tutu/app/controllers/searches_controller.rb
> +  def show_route_trains
Просто Ruby класс - т.е. обычный класс в той же категории моделей, только не унаследованный от ApplicationRecord?

2017-06-14 19:01 UTC, dimasumskoy commented on tutu/app/controllers/searches_controller.rb
> +    @departure_time = @route.railway_stations.first.current_departure_time(@route)
А какую еще информацию? У нас для станций кроме названия, времени прибытия/отправления, ну инфы о поездах на них ничего нет, но т.к. поезда должны показываться в рамках маршрута, то больше вроде и нечего показывать.

2017-06-15 03:08 UTC, iBublik commented on tutu/app/controllers/searches_controller.rb
> +  def find_route_trains
По методологии agile мы делаем то что нужно здесь и сейчас, по необходимости вносим изменеия. Так что сейчас эт лишнее усложнение

2017-06-15 03:12 UTC, iBublik commented on tutu/app/controllers/searches_controller.rb
> +  def show_route_trains
Можно в папку моделей поместить, можно создать папку services и положить туда - тут как больше нравится. Обычно в папке models только active record лежит

2017-06-15 03:13 UTC, iBublik commented on tutu/app/controllers/searches_controller.rb
> +    @departure_time = @route.railway_stations.first.current_departure_time(@route)
Ну когда я ищу информацию по станциям Пермь - Ярославль, мне интересно время прибятия и отправления от этих станций, а не от начальной/конечной

2017-06-15 17:34 UTC, dimasumskoy commented on tutu/app/views/railcars/edit.html.erb
> +<%= render 'form', railcar: @railcar.becomes(Railcar), train: @train %>
Вот здесь не совсем понял, где именно использовать `@railcar.train`? Сейчас при создании вагона из url и так id поезда приходит, и он сразу для него и создается

2017-06-15 18:18 UTC, iBublik commented on tutu/app/views/railcars/edit.html.erb
> +<%= render 'form', railcar: @railcar.becomes(Railcar), train: @train %>
В контроллере при создании вагона - `@railcar = @train.railcars.build`. Тогда можно будет не передавать поезд в партиал, т.к. он будет доступен из вагона (`railcar.train`)

2017-06-16 11:28 UTC, vkurennov approved these changes

2017-06-17 23:01 UTC, merged